channels:
  - https://conda.anaconda.org/conda-forge
  - nodefaults
dependencies:
  - bqplot
  - doit-with-toml
  - flit >=3.9.0,<4
  - git
  - importnb
  - ipydatagrid
  - ipylab >=0.7.0
  - ipywidgets >=8.0.0
  - jupyter_server >=2.2.1
  - jupyterlab >=3,<4
  - jupyterlab >=3.6.4,<3.7
  - jupyterlab-deck
  - jupyterlite-pyodide-kernel ==0.1.1
  - lxml
  - networkx
  - nodejs >=18,<19
  - numcodecs
  - orjson
  - packaging >=22.0
  - pandas
  - pip
  - pytest-asyncio
  - pytest-cov
  - pytest-html
  - pytest-json-report
  - pytest-xdist
  - python =3.11
  - python-dotenv
  - scour
  - stringcase
  - tomli
  - traittypes
