channels:
  - conda-forge
  - nodefaults
dependencies:
  - ansi2html
  - black-jupyter
  - bqplot >=0.12.20
  - docutils >=0.19
  - doit
  - firefox =102
  - flit >=3.7.1,<4
  - geckodriver
  - hypothesis
  - importnb
  - ipydatawidgets
  - ipython >=7
  - ipywidgets >=8.0.1,<9
  - isort
  - jupyterlab >=3,<4
  - jupyterlab-deck
  - jupyterlab-myst
  - jupyterlab-webrtc-docprovider
  - keyring
  - mypy
  - myst-nb
  - networkx
  - nodejs >=18,<19
  - packaging >=22.0
  - pandas
  - pydata-sphinx-theme
  - pyflakes
  - pytest-asyncio
  - pytest-check-links
  - pytest-cov
  - pytest-html
  - pytest-xdist
  - python-libarchive-c
  - requests-cache
  - robotframework-pabot
  - robotframework-robocop
  - robotframework-seleniumlibrary
  - robotframework-tidy
  - rope
  - sphinx
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  - tomli
  - twine
  - wheel
  # lite
  - pip
  - pkginfo
  - python >=3.8,<3.12.0a0
  - pip:
    - jupyterlite ==0.1.0b16
