channels:
  - conda-forge
  - nodefaults
dependencies:
  - black-jupyter
  - firefox =102
  - geckodriver
  - git
  - hypothesis
  - importnb
  - isort
  - jupyterlab-link-share
  - keyring
  - mypy >=1.0.0
  - pyflakes
  - pyproject-fmt
  - pytest-asyncio
  - pytest-check-links
  - pytest-cov
  - pytest-html
  - pytest-xdist
  - requests-cache
  - robotframework-jupyterlibrary
  - robotframework-pabot
  - robotframework-robocop
  - robotframework-tidy
  - rope
  - ssort
  - stringcase
  ### docs/environment.yml ###
  - ansi2html
  - autodoc-traits
  - bqplot >=0.12.20
  - docutils >=0.19
  - doit
  - flit >=3.7.1,<4
  - ipython >=8.10
  - ipywidgets >=8.0.4,<9
  - jupyterlab >=3,<4
  - jupyterlab-deck
  - myst-nb
  - networkx
  - nodejs >=18,<19
  - nomkl
  - numcodecs
  - orjson
  - packaging >=22.0
  - pandas
  - pip
  - pkginfo
  - pydata-sphinx-theme
  - python >=3.8,<3.12.0a0
  - python-libarchive-c
  - sphinx
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - tomli
  - traittypes
  - twine
  - wheel
  ### docs/environment.yml ###
