channels:
  - conda-forge
  - nodefaults
dependencies:
  ### docs/environment.yml ###
  - ansi2html
  - bqplot >=0.12.20
  - docutils >=0.19
  - doit
  - flit >=3.7.1,<4
  - ipython >=7
  - ipywidgets >=8.0.4,<9
  - jupyterlab >=3,<4
  - jupyterlab-deck
  - jupyterlab-myst
  - myst-nb
  - networkx
  - nodejs >=18,<19
  - nomkl
  - numcodecs
  - orjson
  - packaging >=22.0
  - pandas
  - pip
  - pkginfo
  - pydata-sphinx-theme
  - python >=3.8,<3.12.0a0
  - sphinx
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  - tomli
  - traittypes
  - twine
  - wheel
  - python-libarchive-c
  ### docs/environment.yml ###
