channels:
  - conda-forge
  - nodefaults
dependencies:
  - ansi2html
  - autodoc-traits
  - bqplot
  - docutils >=0.19
  - doit-with-toml
  - flit >=3.7.1,<4
  - git
  - importnb
  - ipydatagrid
  - ipylab >=0.7.0
  - ipywidgets >=8.0.0
  - jupyter_server >=2.2.1
  - jupyterlab >=3,<4
  - jupyterlab >=3.6.2,<3.7
  - jupyterlab-deck
  - jupyterlab-link-share
  - jupyterlite-core ==0.1.0
  - jupyterlite-core-with-libarchive
  - jupyterlite-pyodide-kernel ==0.0.8
  - lxml
  - myst-nb
  - networkx
  - nodejs >=18,<19
  - numcodecs
  - orjson
  - packaging >=22.0
  - pandas
  - pip
  - pydata-sphinx-theme
  - pytest-asyncio
  - pytest-cov
  - pytest-html
  - pytest-json-report
  - pytest-xdist
  - python >=3.11,<3.12
  - python >=3.8,<3.12
  - python-dotenv
  - scour
  - sphinx
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - tomli
  - traittypes
