channels:
  - conda-forge
  - nodefaults
dependencies:
  - ansi2html
  - autodoc-traits
  - bqplot >=0.12.20
  - comm >=0.1.3
  - docutils >=0.19
  - doit-with-toml
  - flit >=3.7.1,<4
  - git
  - ipywidgets >=8.0.5,<9
  - jupyterlab >=3,<4
  - jupyterlab >=3.5.2,<3.6
  - jupyterlab-deck
  - jupyterlab-link-share
  - myst-nb
  - nodejs >=18,<19
  - numcodecs
  - packaging >=22.0
  - pandas
  - pip
  - pkginfo
  - pydata-sphinx-theme
  - python >=3.11,<3.12
  - python >=3.8,<3.12
  - python-libarchive-c
  - sphinx
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - tomli
  - traittypes
